import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowLeft, BadgeDollarSign, CheckCircle2, Crown, Flag, Lightbulb, ListChecks, ShieldCheck, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getUseCase } from "@/lib/data";
import { useCasesSeed } from "@/lib/catalog";
type Params = Promise<{ slug: string }>;
export function generateStaticParams(){return useCasesSeed.map((item)=>({slug:item.slug}));}
export async function generateMetadata({params}:{params:Params}):Promise<Metadata>{const item=await getUseCase((await params).slug);return{title:item?.title||"场景指南"};}
export default async function UseCasePage({params}:{params:Params}){const item=await getUseCase((await params).slug);if(!item)notFound();const solutions=[[BadgeDollarSign,"免费方案",item.freeSolution,"bg-emerald-50 text-emerald-700"],[Flag,"推荐方案",item.domesticSolution,"bg-red-50 text-red-700"],[Crown,"效果优先方案",item.strongestSolution,"bg-amber-50 text-amber-700"],[Sparkles,"低成本方案",item.lowCostSolution,"bg-blue-50 text-blue-700"],[ShieldCheck,"高校稳妥方案",item.governmentEducationSolution,"bg-violet-50 text-violet-700"]] as const;return <div className="container max-w-5xl py-10"><Link href="/use-cases" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="size-4" />返回场景推荐</Link><div className="mt-8"><Badge><Lightbulb className="mr-1 size-3" />任务指南</Badge><h1 className="mt-5 text-4xl font-black tracking-tight md:text-5xl">{item.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">{item.description}</p></div><section className="mt-10"><h2 className="text-xl font-black">优先推荐工具</h2><div className="mt-4 flex flex-wrap gap-3">{item.recommendedTools.map((tool,index)=><Link href={`/tools?q=${encodeURIComponent(tool)}`} key={tool} className="rounded-2xl border bg-white px-5 py-4 font-bold shadow-sm hover:border-primary/30"><span className="mr-3 text-sm text-primary">0{index+1}</span>{tool}</Link>)}</div></section><section className="mt-10 grid gap-4 md:grid-cols-2">{solutions.map(([Icon,title,text,color],index)=><Card key={title} className={index===4?"md:col-span-2 border-violet-200":""}><CardContent className="flex gap-4 p-5"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${color}`}><Icon className="size-5" /></span><div><p className="font-bold">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div></CardContent></Card>)}</section><div className="mt-10 grid gap-6 md:grid-cols-[1.3fr_.7fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><ListChecks className="size-5 text-primary" />推荐步骤</CardTitle></CardHeader><CardContent><ol className="space-y-5">{item.steps.map((step,index)=><li key={step} className="flex gap-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-primary text-xs font-bold text-white">{index+1}</span><p className="pt-0.5 text-sm leading-6">{step}</p></li>)}</ol></CardContent></Card><Card className="border-amber-200 bg-amber-50/60"><CardHeader><CardTitle className="flex items-center gap-2 text-amber-900"><AlertTriangle className="size-5" />常见坑</CardTitle></CardHeader><CardContent><ul className="space-y-4">{item.cautions.map((caution)=><li key={caution} className="flex gap-2 text-sm leading-6 text-amber-950/70"><span>•</span>{caution}</li>)}</ul></CardContent></Card></div></div>;}
