"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Check, Edit3, Loader2, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Row = Record<string, unknown> & { id: string };
const labels: Record<string,string>={tools:"工具",agents:"Agent",rankings:"榜单",comparisons:"对比文章","use-cases":"场景",news:"情报"};

export function AdminManager({ entity }: { entity: string }) {
  const [rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[query,setQuery]=useState("");const[showCreate,setShowCreate]=useState(false);const[editing,setEditing]=useState<Row|null>(null);const[notice,setNotice]=useState("");
  const load=useCallback(async(q="")=>{setLoading(true);setError("");try{const response=await fetch(`/api/admin/${entity}${q?`?q=${encodeURIComponent(q)}`:""}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"加载失败");setRows(data);}catch(e){setError(e instanceof Error?e.message:"加载失败");}finally{setLoading(false);}},[entity]);
  useEffect(()=>{load();},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const body=Object.fromEntries(form.entries());const response=await fetch(`/api/admin/${entity}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok){setError(data.error||"创建失败");return;}setShowCreate(false);setNotice("创建成功");load();}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;const body=Object.fromEntries(new FormData(event.currentTarget).entries());const response=await fetch(`/api/admin/${entity}/${editing.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok){setError(data.error||"更新失败");return;}setEditing(null);setNotice("更新成功");load(query);}
  async function remove(row:Row){if(!confirm(`确定删除“${displayName(row)}”？此操作不可恢复。`))return;const response=await fetch(`/api/admin/${entity}/${row.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok){setError(data.error||"删除失败");return;}setNotice("已删除");load(query);}
  return <div>
    <div className="flex flex-wrap items-center gap-3 rounded-2xl border bg-white p-4"><form className="relative min-w-[240px] flex-1" onSubmit={(e)=>{e.preventDefault();load(query);}}><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input value={query} onChange={(e)=>setQuery(e.target.value)} className="h-10 pl-9" placeholder={`搜索${labels[entity]}...`}/></form><Button variant="outline" size="sm" onClick={()=>load(query)}><RefreshCw className="size-4"/>刷新</Button>{entity!=="agents"&&<Button size="sm" onClick={()=>setShowCreate(true)}><Plus className="size-4"/>新增{labels[entity]}</Button>}</div>
    {notice&&<div className="mt-3 flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700"><Check className="size-4"/>{notice}<button className="ml-auto" onClick={()=>setNotice("")}><X className="size-4"/></button></div>}
    {error&&<div className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {showCreate&&<Editor entity={entity} title={`新增${labels[entity]}`} onSubmit={create} onClose={()=>setShowCreate(false)}/>} {editing&&<Editor entity={entity} title={`编辑：${displayName(editing)}`} row={editing} onSubmit={save} onClose={()=>setEditing(null)}/>} 
    <div className="mt-5 overflow-hidden rounded-2xl border bg-white"><div className="grid grid-cols-[1fr_140px_100px] border-b bg-muted/40 px-5 py-3 text-xs font-bold text-muted-foreground md:grid-cols-[1.4fr_1fr_140px_100px]"><span>名称</span><span className="hidden md:block">分类 / 公司</span><span>状态</span><span className="text-right">操作</span></div>{loading?<div className="grid place-items-center py-20"><Loader2 className="size-6 animate-spin text-primary"/></div>:rows.length===0?<div className="py-16 text-center text-sm text-muted-foreground">暂无数据</div>:<div className="divide-y">{rows.map((row)=><div key={row.id} className="grid grid-cols-[1fr_140px_100px] items-center gap-3 px-5 py-4 text-sm md:grid-cols-[1.4fr_1fr_140px_100px]"><div className="min-w-0"><p className="truncate font-bold">{displayName(row)}</p><p className="mt-1 truncate text-xs text-muted-foreground">/{String(row.slug||row.id)}</p></div><div className="hidden min-w-0 md:block"><p className="truncate text-muted-foreground">{String(row.category||row.scenario||row.company||"—")}</p></div><div>{row.isPinned?<Badge>置顶</Badge>:row.recommendationLevel?<Badge variant="outline">推荐 {String(row.recommendationLevel)}</Badge>:row.agentType?<Badge variant="outline">{String(row.agentType)}</Badge>:<Badge variant="secondary">已发布</Badge>}</div><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" onClick={()=>setEditing(row)}><Edit3 className="size-4"/></Button>{entity!=="agents"&&<Button variant="ghost" size="icon" onClick={()=>remove(row)} className="text-destructive"><Trash2 className="size-4"/></Button>}</div></div>)}</div>}</div>
  </div>;
}

function Editor({entity,title,row,onSubmit,onClose}:{entity:string;title:string;row?:Row;onSubmit:(event:FormEvent<HTMLFormElement>)=>void;onClose:()=>void}){
  const fields=useMemo(()=>fieldConfig(entity,row),[entity,row]);return <div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm"><form onSubmit={onSubmit} className="max-h-[88vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-4"><h2 className="font-black">{title}</h2><Button type="button" variant="ghost" size="icon" onClick={onClose}><X className="size-4"/></Button></div><div className="grid gap-4 p-6 sm:grid-cols-2">{fields.map((field)=><label key={field.name} className={field.wide?"sm:col-span-2":""}><span className="mb-1.5 block text-xs font-bold text-muted-foreground">{field.label}</span>{field.type==="select"?<select name={field.name} defaultValue={field.value} className="h-11 w-full rounded-xl border bg-white px-3 text-sm">{field.options?.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:field.type==="textarea"?<textarea name={field.name} defaultValue={field.value} rows={4} className="w-full rounded-xl border bg-white p-3 text-sm outline-none focus:border-primary"/>:<Input name={field.name} type={field.type||"text"} defaultValue={field.value}/>}</label>)}</div><div className="sticky bottom-0 flex justify-end gap-2 border-t bg-white px-6 py-4"><Button type="button" variant="outline" onClick={onClose}>取消</Button><Button>保存</Button></div></form></div>;
}
type Field={name:string;label:string;value:string;type?:string;wide?:boolean;options?:string[][]};
function fieldConfig(entity:string,row?:Row):Field[]{const v=(key:string)=>String(row?.[key]??"");const common=[{name:"title",label:"标题",value:v("title")},{name:"slug",label:"Slug（创建后不可改）",value:v("slug")}];if(entity==="tools"||entity==="agents")return [{name:"name",label:"工具名称",value:v("name")},{name:"company",label:"公司 / 团队",value:v("company")},{name:"officialUrl",label:"官网 / 使用地址",value:v("officialUrl"),wide:true},{name:"slug",label:"Slug",value:v("slug")},{name:"category",label:"分类",value:v("category")||"大模型助手"},{name:"domesticAccessibility",label:"国内可用性",value:v("domesticAccessibility")||"UNKNOWN",type:"select",options:[["DIRECT","国内直连"],["SPECIAL_NETWORK","需特殊网络"],["UNSTABLE","不稳定"],["NOT_RECOMMENDED","不建议"],["UNKNOWN","待核验"]]},{name:"pricingModel",label:"价格模式",value:v("pricingModel")||"FREEMIUM",type:"select",options:[["FREE","免费"],["FREEMIUM","免费增值"],["PAID","付费"],["OPEN_SOURCE","开源免费"],["ENTERPRISE","企业报价"]]},{name:"recommendationLevel",label:"推荐指数",value:v("recommendationLevel")||"80",type:"number"},{name:"agentType",label:"Agent 类型",value:v("agentType")},{name:"shortDescription",label:"一句话简介",value:v("shortDescription"),type:"textarea",wide:true}];if(entity==="rankings")return [...common,{name:"category",label:"分类",value:v("category")},{name:"description",label:"榜单说明",value:v("description"),type:"textarea",wide:true}];if(entity==="comparisons")return [...common,{name:"scenario",label:"适用场景",value:v("scenario")},{name:"toolsCompared",label:"对比对象（逗号分隔）",value:Array.isArray(row?.toolsCompared)?(row?.toolsCompared as string[]).join(","):v("toolsCompared"),wide:true},{name:"summary",label:"摘要",value:v("summary"),type:"textarea",wide:true},{name:"conclusion",label:"结论",value:v("conclusion"),type:"textarea",wide:true},{name:"content",label:"正文",value:v("content"),type:"textarea",wide:true}];if(entity==="use-cases")return [...common,{name:"scenario",label:"场景",value:v("scenario")},{name:"recommendedTools",label:"推荐工具（逗号分隔）",value:Array.isArray(row?.recommendedTools)?(row?.recommendedTools as string[]).join(","):v("recommendedTools"),wide:true},{name:"description",label:"说明",value:v("description"),type:"textarea",wide:true}];return [...common,{name:"category",label:"分类",value:v("category")},{name:"source",label:"来源",value:v("source")},{name:"importanceScore",label:"重要性（1-5）",value:v("importanceScore")||"3",type:"number"},{name:"summary",label:"摘要",value:v("summary"),type:"textarea",wide:true}];}
function displayName(row:Row){return String(row.name||row.title||"未命名");}
