import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, BriefcaseBusiness, Code2, GraduationCap, Image, Lightbulb, Presentation, Search, Workflow } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { getUseCases } from "@/lib/data";
export const metadata: Metadata = { title: "场景推荐", description: "从真实任务出发的 AI 工具选择与使用指南。" };
const icons = [BriefcaseBusiness,BookOpenCheck,Presentation,Search,Code2,Code2,Workflow,Workflow,GraduationCap,GraduationCap,Image,Image,Image,BookOpenCheck,BriefcaseBusiness,Presentation,Search,Workflow];
export default async function UseCasesPage() { const guides = await getUseCases(); return <><section className="border-b bg-white"><div className="container py-14 text-center"><Badge><Lightbulb className="mr-1.5 size-3.5" />从任务出发</Badge><h1 className="mt-5 text-4xl font-black tracking-tight md:text-5xl">我想做这件事，应该用哪个 AI？</h1><p className="mx-auto mt-5 max-w-2xl leading-7 text-muted-foreground">每份指南都给出免费、推荐、效果优先、低成本和高校稳妥方案。</p></div></section><div className="container py-12"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{guides.map((guide,index) => { const Icon=icons[index] || Lightbulb; return <Link href={`/use-cases/${guide.slug}`} key={guide.id}><Card className="group h-full hover:-translate-y-1 hover:border-primary/30 hover:shadow-soft"><CardContent className="p-6"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-primary/8 text-primary"><Icon className="size-5" /></span><span className="text-xs font-black text-muted-foreground">{String(index+1).padStart(2,"0")}</span></div><h2 className="mt-5 text-lg font-black group-hover:text-primary">{guide.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-muted-foreground">{guide.description}</p><div className="mt-5 flex flex-wrap gap-1.5">{guide.recommendedTools.slice(0,3).map((tool) => <Badge key={tool} variant="outline">{tool}</Badge>)}</div><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-primary">查看方案 <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></CardContent></Card></Link>; })}</div></div></>; }
