import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, Crown, ExternalLink, Medal, Star, Trophy, Users } from "lucide-react";
import { ToolAvatar } from "@/components/tool-avatar";
import { AnimatedCard } from "@/components/animated-card";
import { RatingBar } from "@/components/rating-bar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getRankings } from "@/lib/data";
import { nationwideUsageRanking, usageRankingMeta } from "@/lib/curated";

export const metadata: Metadata = { title: "AI 模型榜单", description: "面向中文用户真实任务的 AI 工具与模型实用榜单。" };
export default async function RankingsPage() {
  const rankings = await getRankings();
  return <>
    <section className="overflow-hidden border-b bg-slate-950 text-white"><div className="container relative py-16"><div className="absolute right-0 top-0 size-72 rounded-full bg-indigo-500/20 blur-3xl" /><Badge className="bg-white/10 text-indigo-200"><Trophy className="mr-1.5 size-3.5" />公开数据 · 任务精选</Badge><h1 className="text-balance mt-5 max-w-4xl text-4xl font-black tracking-tight md:text-5xl">全国使用热度与 <span className="text-indigo-300">13 个任务精选榜</span></h1><p className="mt-5 max-w-2xl leading-7 text-slate-400">使用热度采用公开月活口径；任务榜同时评估完成质量、中文工作流、上手成本和高校使用边界。</p><div className="mt-8 flex flex-wrap gap-2">{rankings.map((item) => <a href={`#${item.slug}`} key={item.slug} className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-slate-300 hover:bg-white/10">{item.title}</a>)}</div></div></section>
    <div className="container py-12">
      <section className="rounded-3xl border bg-white p-6 shadow-sm md:p-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Badge><Users className="mr-1.5 size-3.5" />全国 AI 工具使用率参考榜</Badge><h2 className="mt-4 text-balance text-2xl font-black md:text-3xl">按公开月活跃用户规模排序</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">{usageRankingMeta.period} · {usageRankingMeta.metric}</p></div><a href={usageRankingMeta.sourceUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-sm font-semibold text-primary">查看数据来源 <ExternalLink className="size-4" /></a></div><div className="mt-7 space-y-3">{nationwideUsageRanking.map((item,index) => { const widths = [100,48,37,17,8,4,2]; const name = item.slug ? <Link href={`/tools/${item.slug}`} className="font-bold hover:text-primary">{item.name}</Link> : <span className="font-bold">{item.name}</span>; return <div key={item.name} className="grid grid-cols-[36px_minmax(80px,150px)_1fr_78px] items-center gap-3"><span className={`grid size-8 place-items-center rounded-lg text-xs font-black ${item.rank <= 3 ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-500"}`}>{item.rank}</span>{name}<div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-violet-500" style={{ width: `${Math.max(widths[index], 3)}%` }} /></div><span className="text-right text-sm font-black text-slate-700">{item.monthlyActiveUsers}</span></div>; })}</div><p className="mt-6 border-t pt-5 text-xs leading-6 text-muted-foreground">{usageRankingMeta.note}</p></section>
      <div className="mt-12 grid gap-7 lg:grid-cols-2">{rankings.map((ranking,rankingIndex) => <AnimatedCard key={ranking.id} delay={rankingIndex*.035}><Card id={ranking.slug} className="scroll-mt-24 overflow-hidden transition-colors duration-300 hover:border-primary/30"><CardHeader className="border-b bg-muted/30"><div className="flex items-start justify-between"><div><Badge variant="outline">{ranking.category}</Badge><CardTitle className="mt-3 text-xl">{ranking.title}</CardTitle><p className="mt-2 text-sm text-muted-foreground">{ranking.description}</p></div><BarChart3 className="size-7 text-primary/40" /></div></CardHeader><CardContent className="p-0"><div className="divide-y">{ranking.items.map((item) => { const entity = item.tool || item.model; if (!entity) return null; const isTool = Boolean(item.tool); return <div key={item.id} className={`grid grid-cols-[40px_1fr_92px] items-center gap-3 p-4 transition-colors duration-300 ${item.rank === 1 ? "border-l-4 border-amber-400 bg-gradient-to-r from-amber-50 to-white" : item.rank === 2 ? "bg-slate-50/80" : item.rank === 3 ? "bg-orange-50/50" : "hover:bg-muted/30"}`}><span className={`grid place-items-center rounded-xl text-sm font-black ${item.rank === 1 ? "size-10 bg-gradient-to-br from-amber-300 to-amber-500 text-white shadow-md" : item.rank === 2 ? "size-8 bg-slate-200 text-slate-600" : item.rank === 3 ? "size-8 bg-orange-100 text-orange-700" : "size-8 text-muted-foreground"}`}>{item.rank}</span><div className="flex min-w-0 items-center gap-3">{isTool && <ToolAvatar name={entity.name} className="size-9 rounded-xl text-xs" />}<div className="min-w-0"><Link href={isTool ? `/tools/${item.tool!.slug}` : "#"} className="line-clamp-1 text-sm font-bold hover:text-primary">{entity.name}</Link><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{item.reason}</p></div></div><div className="text-right"><p className="mb-1 flex items-center justify-end gap-1 text-sm font-black text-primary"><Star className="size-3 fill-current" />{item.score.toFixed(1)}</p><RatingBar value={item.score} showValue={false}/></div></div>; })}</div></CardContent></Card></AnimatedCard>)}</div>
      <div className="mt-10 rounded-2xl border border-dashed p-6 text-center text-sm text-muted-foreground">榜单为编辑部人工评分，适合缩小候选范围，不等同于标准化评测。正式选型请使用真实业务样例验证。</div>
    </div>
  </>;
}
